---
- name: create page_cache directory
  file:
    recurse=yes
    path={{ project_cache_page_enhanced_folder }}
    mode=0777
    state=directory

- name: create upload directory
  file:
    recurse=yes
    path={{ project_upload_folder }}
    mode=0777
    state=directory

- name: copy over to /etc/exports
  template:
    src=exports.j2
    dest=/etc/exports
  notify: restarting nfs
