---
- name: install yum packages
  sudo: true
  yum:
    name={{item}}
    state=latest
  with_items:
    - vim
    - screen
    - git
  tags:
    - common

- name: Add mariadb repo
  sudo: True
  copy:
    src=mariadb.repo
    dest=/etc/yum.repos.d/mariadb.repo
