---
- name: add the group www-data
  group:
    name={{ project_group }}
    state=present

- name: add the user www-data
  user:
    name={{ project_user }}
    group={{ project_group }}

- name: create wordpress directory
  file:
    recurse=yes
    path={{ project_folder }}
    owner={{ project_user }}
    group={{ project_group }}
    mode=0755
    state=directory

- name: install core packages for frontend
  yum:
    name={{item}}
    state=latest
  with_items:
    - php
    - php-cli
    - php-mysql
    - MariaDB-client
    - php-fpm

- name: restart php-fpm
  sudo: true
  service:
    name=php-fpm
    state=restarted
    enabled=yes

- include: wp-cli.yml
- include: wordpress-core.yml
