---
- name: add the group www-data
  sudo: True
  group:
    name={{ project_group }}
    state=present

- name: add the user www-data
  sudo: True
  user:
    name={{ project_user }}
    group={{ project_group }}

- name: create wordpress directory
  sudo: True
  file:
    recurse=yes
    path={{ project_folder }}
    owner={{ project_user }}
    group={{ project_group }}
    mode=0755
    state=directory

- name: install core packages for frontend
  sudo: true
  yum:
    name={{item}}
    state=latest
  with_items:
    - php
    - php-cli

- include: wp-cli.yml
- include: wordpress-core.yml
