---
- name: Check if /usr/local/bin/wp file already exists.
  stat: "path={{ project_folder }}/wp-config.php"
  register: wp_config_file

- name: download wordpress core
  shell: 'cd {{ project_folder }};/usr/local/bin/{{ item }}'
  with_items:
  - wp core download
  when: wp_config_file.stat.exists == false
  ignore_errors: yes

- name: download salts
  get_url:
    url=https://api.wordpress.org/secret-key/1.1/salt/
    dest={{ project_folder }}/wp-salts
    mode=0755

- name: register salts variable
  shell: 'cat {{ project_folder }}/wp-salts'
  register: salts

- name: add config file
  template:
    src=wp-config.php
    dest={{ project_folder }}/wp-config.php
  notify: set owner and group
