---
- name: Check if /usr/local/bin/wp file already exists.
  stat: "path=/usr/local/bin/wp"
  register: wp_file

- name: download wp-cli
  command: "curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
  when: wp_file.stat.exists == false

- name: make wp-cli.phar executable
  command: chmod +x wp-cli.phar
  when: wp_file.stat.exists == false

- name: make wp usable over the system
  command: mv wp-cli.phar /usr/local/bin/wp
  when: wp_file.stat.exists == false
