---

- name: Add repo for nginx centos 7
  yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm state=present

- name: Install the selinux python module
  yum: name=libselinux-python state=present
  when: ansible_os_family == "RedHat"
  tags: [packages,nginx]

- name: Copy the epel packages
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel_ansible.repo
  when: nginx_is_el|bool
  tags: [packages,nginx]

- name: Install the nginx packages
  yum: name={{ item }} state=present
  with_items: nginx_redhat_pkg
  when:  nginx_is_el|bool
  tags: [packages,nginx]

- name: Install the nginx packages
  yum: name={{ item }} state=present
  with_items: nginx_redhat_pkg
  when: ansible_os_family == "RedHat" and not nginx_is_el|bool
  tags: [packages,nginx]

- name: Install the nginx packages
  apt: name={{ item }} state=present
  with_items: nginx_ubuntu_pkg
  environment: env
  when: ansible_os_family == "Debian"
  tags: [packages,nginx]
