---
- name: install yum update
  shell: yum -y update

- name: install yum packages
  sudo: true
  yum:
    name={{item}}
    state=latest
  with_items:
    - vim
    - screen
    - git
  tags:
    - common
