---
- name: Setup database server
  remote_user: root
  hosts: db
  sudo: true
  roles:
    - { role: common, tags: ['setup'] }
    - { role: geerlingguy.nfs, tags: ['setup', 'nfs'] }
    - { role: geerlingguy.firewall, tags: ['setup'] }
    - { role: mariadb, tags: ['setup'] }
    - { role: hb-database, tags: ['deploy', 'db'] }
