---

- hosts: db
  name: Gather facts from databaseservers
  tasks: [ ]

- name: Setup frontend servers
  remote_user: root
  hosts: web
  sudo: True
  roles:
    - { role: common, tags: ['setup'] }
    - { role: geerlingguy.nfs, tags: ['setup'] }
    - { role: geerlingguy.firewall, tags: ['setup', 'firewall'] }
    - { role: hb-web }
