---
- name: restart php-fpm
  sudo: true
  service:
    name=php-fpm
    state=restarted
    enabled=yes

- name: set file permissions
  command: pwd
  notify:
    - register wp-config.php file
    - set owner and group www-data
    - ensure directories are 0755
    - ensure files are 0644
    - ensure file wp-config is 0660

- name: register wp-config.php file
  stat: "path={{ project_folder }}/wp-config.php"
  register: wp_config_file

- name: set owner and group www-data
  command: find {{ project_folder }} -path {{ project_folder }}/wp-content/upload -prune -o -exec chown {{ project_user }}:{{ project_group }} {} \;

- name: ensure directories are 0755
  command: find {{ project_folder }} -path {{ project_folder }}/wp-content/upload -prune -o -type d -exec chmod 0775 {} \;

- name: ensure files are 0644
  command: find {{ project_folder }} -path {{ project_folder }}/wp-content/upload -prune -o -type f -exec chmod 0644 {} \;

- name: ensure file wp-config is 0660
  file:
    path={{ project_folder }}/wp-config.php
    owner={{ project_user }}
    group={{ project_group }}
    mode=0660
  when: wp_config_file.stat.exists == true

