---
- name: copy key
  sudo: true
  copy:
    src=nginx_signing.key
    dest=/root/nginx_signing.key

- name: add nginx key
  sudo: true
  apt_key:
    file=/root/nginx_signing.key

- name: add nginx to sources
  sudo: true
  apt_repository:
    repo="{{ item }}"
    state=present
    update_cache=true
  with_items:
    - "deb http://nginx.org/packages/debian/ wheezy nginx"
    - "deb-src http://nginx.org/packages/debian/ wheezy nginx"

- name: install nginx
  sudo: true
  apt:
    name=nginx
    state=present

- name: nginx settings
  sudo: true
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
