---
- name: add the group www-data
  group:
    name={{ project_group }}
    state=present

- name: add the user www-data
  user:
    name={{ project_user }}
    group={{ project_group }}

- name: install core packages for frontend
  yum:
    name={{item}}
    state=latest
  with_items:
    - php
    - php-cli
    - php-mysql
    - MariaDB-client
    - php-fpm

- name: install w3 total cache packages
  yum:
    name={{item}}
    state=latest
  with_items:
    - php-pear
    - php-devel
    - httpd-devel
    - gcc
    - zlib-devel
    - pcre-devel

- name: add w3 cache dummy file
  template:
    src=w3c.dummy.nginx.conf.j2
    dest={{ project_folder }}/nginx.conf
  notify:
    - set file permissions
    - restart nginx
