---
- name: add the group www-data
  group:
    name={{ project_group }}
    state=present

- name: add the user www-data
  user:
    name={{ project_user }}
    group={{ project_group }}

- name: install python librarys for selinux
  yum:
    name={{ item }}
    state=latest
  with_items:
    - libsemanage-python
