---
- name: add the group www-data
  group:
    name={{ project_group }}
    state=present

- name: add the user www-data
  user:
    name={{ project_user }}
    group={{ project_group }}

- name: install docker
  yum:
    name=docker
    state=latest
  notify:
    - restart docker

- name: install selinux esentials
  yum:
    name=libsemanage-python
    state=latest
