---
- name: create nfs directory
  file:
    recurse=yes
    path={{ item }}
    owner={{ project_user }}
    group={{ project_group }}
    mode=0755
    state=directory
  with_items:
    - nfs_folders

- mount:
    name="{{ item }}"
    src="{{ hostvars[groups['db'][0]]['ansible_ssh_host'] }}":"{{ item }}"
    fstype=nfs
    state=mounted
  with_items:
    - nfs_folders
