---
- name: create wordpress directory
  command: mkdir -p {{ project_folder }}

- name: register wp-config.php file
  stat: "path={{ project_folder }}/wp-config.php"
  register: wp_config_file

- name: register index.php file
  stat: "path={{ project_folder }}/index.php"
  register: wp_index_file

- name: download wordpress core
  shell: 'cd {{ project_folder }};/usr/local/bin/{{ item }}'
  sudo_user: "{{ project_user }}"
  with_items:
  - wp core download
  when: wp_index_file.stat.exists == false
  notify:
    - set file permissions

- name: download salts
  get_url:
    url=https://api.wordpress.org/secret-key/1.1/salt/
    dest={{ project_folder }}/wp-salts
    mode=0755

- name: register salts variable
  shell: 'cat {{ project_folder }}/wp-salts'
  register: salts

- name: add config file
  template:
    src=wp-config.php
    dest={{ project_folder }}/wp-config.php
  notify:
    - set file permissions
    - restart php-fpm
