- name: install w3 total cache packages
  yum:
    name={{item}}
    state=latest
  with_items:
    - php-pear
    - php-devel
    - httpd-devel
    - gcc
    - zlib-devel
    - pcre-devel
  tags:
    - setup

- name: add w3 cache dummy file
  template:
    src=w3c.dummy.nginx.conf.j2
    dest={{ project_folder }}/nginx.conf
  notify:
    - set file permissions
    - restart nginx
  tags:
    - setup

- name: remove php-curl extesion for w3 total cache to work
  file:
    path: /etc/php.d/curl.ini
    state: absent
  notify:
    - restart php-fpm
  tags:
    - deploy

- name: create cache config directory
  file:
    recurse=yes
    path={{ project_folder }}/wp-content/w3tc-config
    owner={{ project_user }}
    group={{ project_group }}
    mode=0755
    state=directory

- name: add w3 cache config file
  template:
    src=w3c.config.master.php
    dest={{ project_folder }}/wp-content/w3tc-config/master.php
  notify:
    - set file permissions
  tags:
    - deploy
